version: 2
updates:
  - package-ecosystem: "github-actions"
    assignees:
      - "kernelsam"
    cooldown:
      default-days: 21
      exclude:
        - "senzing-factory/*"
    directory: "/"
    groups:
      senzing-factory:
        patterns:
          - "senzing-factory/*"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    cooldown:
      default-days: 21
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    cooldown:
      default-days: 21
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    cooldown:
      default-days: 21
    directory: "/java/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    cooldown:
      default-days: 21
    directories:
      - /csharp/snippets/configuration/InitDefaultConfig/
      - /csharp/snippets/configuration/RegisterDataSources/
      - /csharp/snippets/information/GetVersion/
      - /csharp/snippets/information/CheckRepositoryPerformance/
      - /csharp/snippets/information/GetRepositoryInfo/
      - /csharp/snippets/information/GetLicense/
      - /csharp/snippets/loading/LoadWithStatsViaLoop/
      - /csharp/snippets/loading/LoadViaLoop/
      - /csharp/snippets/loading/LoadWithInfoViaFutures/
      - /csharp/snippets/loading/LoadViaFutures/
      - /csharp/snippets/loading/LoadRecords/
      - /csharp/snippets/loading/LoadViaQueue/
      - /csharp/snippets/loading/LoadTruthSetWithInfoViaLoop/
      - /csharp/snippets/redo/LoadWithRedoViaLoop/
      - /csharp/snippets/redo/RedoContinuousViaFutures/
      - /csharp/snippets/redo/RedoWithInfoContinuous/
      - /csharp/snippets/redo/RedoContinuous/
      - /csharp/snippets/searching/SearchViaFutures/
      - /csharp/snippets/searching/SearchRecords/
      - /csharp/snippets/initialization/EnginePriming/
      - /csharp/snippets/initialization/PurgeRepository/
      - /csharp/snippets/initialization/EnvironmentAndHubs/
      - /csharp/snippets/stewardship/ForceUnresolve/
      - /csharp/snippets/stewardship/ForceResolve/
      - /csharp/snippets/deleting/DeleteViaLoop/
      - /csharp/snippets/deleting/DeleteViaFutures/
      - /csharp/snippets/deleting/DeleteWithInfoViaFutures/
      - /csharp/runner/SnippetRunner/
    groups:
      all:
        patterns:
          - "*"
        exclude:
          - "Senzing.Sdk"
    ignore:
      - dependency-name: "Senzing.Sdk"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    include:
      - "Senzing.Sdk"
    schedule:
      interval: "daily"
